# Site settings
title: Rahul | Web | iOS 
description: Full stack freelance developer working remote full time
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rahul Choudhary
user_description: Hi, I am a full stack developer working remotely on web and iOS currently located in India. 
user_title: Software developer
email: rahul@rahulchoudhary.dev
twitter_username: _rchoudhary
github_username:  r-choudhary
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
